// src/webapp/src/app/app.component.ts
import { Component } from '@angular/core';
import { ROUTER_DIRECTIVES } from '@angular/router';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
    directives: [ROUTER_DIRECTIVES]
})
export class AppComponent {
  title = 'app works!';
}

<body>
<div id="wrap">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" [routerLink]="['/']">ECE 350 Assembler</a>
        </div>
        <div class="collapse navbar-collapse" id="example-navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a [routerLink]="['/']" class="btn">Home</a></li>
            <li><a [routerLink]="['/assembler']" class="btn">Assembler</a></li>
            <li><a [routerLink]="['/about']" class="btn">About</a></li>
          </ul>
        </div>
      </div>
    </nav>
</div>
<div class="container">
  <!-- Routed views go here -->
  <router-outlet></router-outlet>
</div>
<footer>
  <div class="container text-center">
    <p>
      <a href="https://github.com/jiaweizhang/assembler-disassembler-simulator" target="_blank"><i class="fa fa-github fa-3x"></i></a>
    </p>

    <p>&copy; Jiawei Zhang, 2016. All rights reserved.</p>
  </div>
</footer>
</body>

// src/main/webapp/src/App.vue
<template>
  <div>
    <div class="wrap">
      <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <router-link class="navbar-brand" to="/">ADS</router-link>
          </div>
          <ul class="nav navbar-nav">
            <li>
              <router-link to="/assembler">Assembler</router-link>
            </li>
            <li>
              <router-link to="/simulator">Simulator</router-link>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <router-link to="/about">About</router-link>
            </li>
          </ul>
        </div>
      </nav>
      <div class="container">
        <router-view></router-view>
      </div>
    </div>
    <div class="footer">
      <div class="container text-center">
        <div>
          <a href="https://github.com/jiaweizhang/assembler-disassembler-simulator" target="_blank"><i
            class="fa fa-github fa-3x"></i></a>
        </div>
        <p>&copy; Jiawei Zhang, 2016. All rights reserved.</p>
      </div>
    </div>
  </div>
</template>


<script>

export default {
}




</script>
