// webapp/src/components/App.vue
<template>
  <div id="wrap">
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <li><a class="navbar-brand" v-link="{path: '/'}">ADS</a></li>
        </div>
        <ul class="nav navbar-nav">
          <li><a v-link="{path: '/assembler'}">Assembler</a></li>
          <li><a v-link="{path: '/disassembler'}" v-if="user.authenticated">Disassembler</a></li>
          <li><a v-link="{path: '/simulator'}" v-if="user.authenticated">Simulator</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a v-link="{path: '/assembler/history'}" v-if="user.authenticated">Assembler History</a></li>
          <li><a v-link="{path: '/about'}">About</a></li>
          <li><a v-link="{path: '/login'}" v-if="!user.authenticated">Login</a></li>
          <li><a v-link="{path: '/signup'}" v-if="!user.authenticated">Sign Up</a></li>
          <li><a v-link="'login'" v-if="user.authenticated" @click="logout()">Logout</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <router-view></router-view>
    </div>
  </div>
  <div id="footer">
    <div class="container text-center">
      <p>
        <a href="https://github.com/jiaweizhang/assembler-disassembler-simulator" target="_blank"><i class="fa fa-github fa-3x"></i></a>
      </p>

      <p>&copy; Jiawei Zhang, 2016. All rights reserved.</p>
    </div>
  </div>
</template>

<script>
  import auth from '../auth'

  export default {
    data() {
      return {
        user: auth.user
      }
    },

    methods: {

      logout() {
        auth.logout()
      }
    }
  }
</script>

// src/webapp/src/app/app.component.ts
import { Component } from '@angular/core';
import { ROUTER_DIRECTIVES } from '@angular/router';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
    directives: [ROUTER_DIRECTIVES]
})
export class AppComponent {
  title = 'app works!';
}

<body>
<div id="wrap">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" [routerLink]="['/']">ECE 350 Assembler</a>
        </div>
        <div class="collapse navbar-collapse" id="example-navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a [routerLink]="['/']" class="btn">Home</a></li>
            <li><a [routerLink]="['/assembler']" class="btn">Assembler</a></li>
            <li><a [routerLink]="['/about']" class="btn">About</a></li>
          </ul>
        </div>
      </div>
    </nav>
</div>
<div class="container">
  <!-- Routed views go here -->
  <router-outlet></router-outlet>
</div>
<footer>
  <div class="container text-center">
    <p>
      <a href="https://github.com/jiaweizhang/assembler-disassembler-simulator" target="_blank"><i class="fa fa-github fa-3x"></i></a>
    </p>

    <p>&copy; Jiawei Zhang, 2016. All rights reserved.</p>
  </div>
</footer>
</body>
